services:
  db:
    image: postgres:17-alpine
    container_name: dj-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: djuser
      POSTGRES_PASSWORD: dj_pass_8291
      POSTGRES_DB: djcafe
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dj-app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    depends_on:
      - db

volumes:
  postgres_data:
